### ISSUE TITLE
Erro HTTP 500

### ISSUE THREAD

**Issue by rodsonwebdesigner** [mariosam/EstimateCEP-M1#1]
Olá!

Instalei o módulo na minha versão 1.9.2.4, porém quando clico na opção C.E.P Frete no admin, apresenta o erro HTTP 500.

No log aparece o seguinte:

> Mage_Core_Exception: Tipo de bloco inválido: MarioSAM_EstimateCep_Block_Estimatecepblock in /.../public_html/app/Mage.php:598
Stack trace:
#0 /.../public_html/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Tipo de bloco i...')
#1 /.../public_html/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('MarioSAM_Estima...', Array)
#2 /.../public_html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('estimatecep/est...', 'calculate_cep_p...')
#3 /.../public_html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('estimatecep/est...', 'calculate_cep_p...')
#4 /.../public_html/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /.../public_html/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /.../public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /.../public_html/app/code/core/Mage/Catalog/Helper/Product/View.php(73): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /.../public_html/app/code/core/Mage/Catalog/Helper/Product/View.php(144): Mage_Catalog_Helper_Product_View->initProductLayout(Object(Mage_Catalog_Model_Product), Object(Mage_Catalog_ProductController))
#9 /.../public_html/app/code/core/Mage/Catalog/controllers/ProductController.php(132): Mage_Catalog_Helper_Product_View->prepareAndRender(268, Object(Mage_Catalog_ProductController), Object(Varien_Object))
#10 /.../public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Catalog_ProductController->viewAction()
#11 /.../public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#12 /.../public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /.../public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 /.../public_html/app/Mage.php(686): Mage_Core_Model_App->run(Array)
#15 /.../public_html/index.php(83): Mage::run('', 'store')
#16 {main}

**Comment by mariosam** [comment]
grande rodson,
vc fez o logout/login no admin depois da instalar!?
as vezes esse "reload" de login atualiza os arquivos XMLs dos modulos instalados e resolve alguns problemas. :)

mas to achando q o problema eh outro..
vi algumas pessoas relatando problemas de case sensitive com modulos para M1.
ali no nome do bloco: Estimatecepblock
se nao me engano, eu criei como EstimateCepBlock.. e seu sistema esta buscando como Estimatecepblock
ai nao encontra, e gera esse erro.

tente alterar o nome do arquivo..para coincidir o nome (maiusculas e minusculas)
depois limpe todos os caches, e faça o logout/login.

**Comment by rodsonwebdesigner** [comment]
Meu nobre,

Fiz o logout e mesmo assim não tive sucesso.

Fiz o ajuste lá no nome do arquivo na pasta block. O erro não aparece mais no log, mas ainda assim continua dando ERRO 500 ao tentar entrar nas configurações.

Obrigado.

**Comment by rodsonwebdesigner** [comment]
Olá, meu nobre.

Consegue me ajudar neste problema?


Obrigado

**Comment by mariosam** [comment]
grande @rodsonwebdesigner 
renomeei o arquivo, para deixar em capitalize
e renomeei as referencias para o proprio arquivo dentro da classe.
espero q isso resolva o problema.
pode baixar esta nova versao.. limpar o cache.. e ve se continua dando erro 500.

**Comment by rodsonwebdesigner** [comment]
Olá meu nobre @mariosam 

Com a correria aqui, não consegui dar um retorno. Mas o problema persiste ainda.

Uma coisa que achei estranha foi que instalei esta extensão em localhost e funcionou, mas quando vou para a versão de produção ainda continua dando erro 500.

Detalhe: a versão de produção está hospedada no Hostgator.
